name: PDF-Sanitiser
#on:
  #workflow_dispatch:
### Auto trigger!
on:
  push:
    paths:
      - 'input/*.pdf'
jobs:
  sanitise:
    runs-on: ubuntu-24.04
    steps:
      - name: auschecken
        uses: actions/checkout@v4
      - name: mupdf und ghostscript installieren
        run: |
          sudo apt-get update
          sudo apt-get install -y mupdf-tools ghostscript
      - name: PDFs bereinigen
        run: /bin/bash ./sanitise.sh
      - name: PDF hochladen
        uses: actions/upload-artifact@v4
        with:
          name: sanitised-pdfs
          path: output/*.pdf
          if-no-files-found: error
